---
title: "PIvot_Lobsters"
author: "David Miller"
date: "1/27/2020"
output: html_document
---

Attaching our packages and reading in data
```{r}
library(tidyverse)
library(readxl)
library(here)
library(skimr) #install.packages("skimr")
library(kableExtra) #install.packages("kableExtra")
# read in lobster data
lobsters <- read_xlsx(here("data", "lobsters.xlsx"),
                      skip=4)

```
#skimr
```{r}
skimr::skim(lobsters)

```
#pivot tables
#"n()" function will count observations
```{r}
#group by year
lobsters %>%
  group_by(year) %>%
  summarize(count_by_year = n())
#group by year and site
lobsters %>%
  group_by(year,site) %>%
  summarize(count_by_yearsite = n())
```
```{r}
#group by site and year
lobsters %>%
  group_by(site,year) %>%
  summarize(count_by_site_year = n())
```

```{r}
lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_site_year = n(),
            mean_size_mm = mean(size_mm, na.rm=TRUE),
            sd_size_mm=sd(size_mm, na.rm=TRUE))
```

#Table formatting with "kableExtra::kable()"
```{r}
#site
```

There are `r nrow(lobsters)` included in this report


## Activity
1.  build from our analyses: calculate the median lobster size for each site and year
(hint: `size_mm` and a function called `median()`

```{r}
lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_site_year = n(),
            median_size_mm = median(size_mm, na.rm=TRUE))
siteyear_summary <-lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_site_year = n(),
            median_size_mm = median(size_mm, na.rm=TRUE))
ggplot(data = siteyear_summary, aes(x=year, y=
                                      median_size_mm, color=site)) +
  geom_line()
        
```

